language: clojure

# Don't use the Travis Container-Based Infrastructure
sudo: true

before_script:
    - which phantomjs
    - phantomjs -v
    - lein cljsbuild test

script:
    - lein doo phantom test once

after_success:
    - lein do clean, cljsbuild once min, less once

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_DEPLOY # Set in travis-ci.org dashboard
    local_dir: resources/public
    on:
        branch: master

